In [199]:
import numpy as np
def max_benefit(invest_benefit,total_money):
    product_num = len(invest_benefit[0])#
    
    decision_old = np.zeros((total_money,product_num))
    decision_new = np.zeros((total_money,product_num))
    decision_old[:,0] = np.array([range(1,total_money+1)])
    
    decision_new[:,:] = decision_old[:,:]
    
    
    if(invest_benefit.shape[0]<total_money):
        print("Each project’s benefit respectively corresponding to 1-n must be given as initial condition")
        return 
    
    max_benefit = np.zeros((total_money+1,product_num))
    invest_benefit = np.insert(invest_benefit, 0, np.zeros(product_num), axis=0)
    
    
    max_benefit[1:total_money+1,0] = invest_benefit[1:total_money+1,0]
    
        
    for k in range(1,product_num):
        for x in range(1,total_money+1):
            temp = [invest_benefit[i,k] + max_benefit[x-i,k-1] for i in range(x+1)]
            index = np.argmax(temp)
            
            max_benefit[x,k] = max(temp)
            
            if index != 0:
                decision_new[x-1,:] = np.zeros(product_num)
                
            if index != x:
                decision_new[x-1,:] = decision_old[x-index-1,:]   
            decision_new[x-1,k] = index
            
        decision_old[:,:] = decision_new[:,:]
    print("f_i(x):\n",max_benefit[1:,:])
    print("maximum:",max_benefit[-1,-1])
    print("decision vector:",decision_new[-1,:])
    
    return max_benefit[total_money,product_num-1]

In [202]:
invest_benefit=np.array([[11,0,2,20],
                [12,5,10,21],
                [13,10,30,22],
                [14,15,32,23],
                [15,20,40,24]
               ])


max_benefit(invest_benefit,5)


f_i(x):
 [[11. 11. 11. 20.]
 [12. 12. 13. 31.]
 [13. 16. 30. 33.]
 [14. 21. 41. 50.]
 [15. 26. 43. 61.]]
maximum: 61.0
decision vector: [1. 0. 3. 1.]


61.0

In [205]:
max_benefit(invest_benefit,4)

f_i(x):
 [[11. 11. 11. 20.]
 [12. 12. 13. 31.]
 [13. 16. 30. 33.]
 [14. 21. 41. 50.]]
maximum: 50.0
decision vector: [0. 0. 3. 1.]


50.0

In [206]:
max_benefit(invest_benefit,6)

Each project’s benefit respectively corresponding to 1-n must be given as initial condition
